### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by bartrylant** [KuriousAgency/craft-barcode#1]
When trying to generate a barcode, I get this error:

```
Array and string offset access syntax with curly braces is deprecated
1. in /Users/***/Sites/***/vendor/kuriousagency/barcode/src/services/BarcodeService.phpat line 208
199200201202203204205206207208209210211212213214215216217            $upce = true; // UPC-E mode
        }
        $data_len = $len;// - 1;
        //Padding
        $code = str_pad($code, $data_len, '0', STR_PAD_LEFT);
        $code_len = strlen($code);
        // calculate check digit
        $sum_a = 0;
        for ($i = 1; $i < $data_len; $i += 2) {
            $sum_a += $code{$i};
        }
        if ($len > 12) {
            $sum_a *= 3;
        }
        $sum_b = 0;
        for ($i = 0; $i < $data_len; $i += 2) {
            $sum_b += ($code{$i});
        }
        if ($len < 13) {
```

**Comment by scandella** [comment]
@bartrylant, same issue for me using PHP 7.4.x.
Downgrading to PHP 7.3.x is a possible solution.
To fix the problem, the code need to be edited and the curly braces need to be replaced by [].
[See this](https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated).

Hope KuriousAgency will do the changes.

**Comment by jamiematrix** [comment]
Are there any plans to fix this for Craft 3? I've updated a site to run on PHP 8.1 from PHP 7.3 and came across this error, so have had to make a manual fix
